void printRules(){
        int scan;
        printf("Roll dice, buy property, win!!");
        printf("More Rules? (1 = yes, 0 = no)");
        scanf("%d", &scan);
        if(scan == 1){
                printf("Pass Go: when the user passes go they collect $200\n");
                printf("The user will be asked to roll 1, sell/buybackproperty 2, Rules 3, buying houses 4,  5 to exit the game\n");
                printf("sell/buybackproperty: asks the user to input 1 or 2 to go between sell and buyback\n");
                printf("Sell: prints all propertiets owned, then asks for input for what property to mortgage\n");
                printf("Buy Back: prints all properties that are mortgaged and asks for input\n");
                printf("Win: if one player's money is below zero and they own no properties\n");
                printf("Jail: three doubles in a row gets you in jail, landing on go to jail gets you in jail; to get out a doubles needs to be rolled, pay $50 dollars, or miss three throws and then pay $50\n");
                printf("Chance and Chest cards are drawn then read off and inacted\n");
                printf("If a property is mortgaged and has houses on it the other player can buy said houses and property if they land on the location");
                printf("More Rules? (1 = yes, 0 = no)");
                scanf("%d", &scan);
                if(scan == 1){

                        printf("Object: The object of the game is become the wealthiest player through buying, renting and selling property. \n");
                        printf("Equipment: The equipment consists of a board, 2 dice, tokens, 32 houses and 12 hotels. There are 16 Chance and 16 Community Chest cards, a Title Deed card for each property (28 total) and play money (7 denominations, 30+ copies of each). \n");
                        printf("Preparation: Place the board on a table and put the Chance and Community Chest cards shuffled & face down on their allotted spaces on the board. Each player chooses one token to represent him/her on his/her travels around the board. Each player is given $1,500 divided as follows: 2x $500's; 4x $100's; 1x $50; 1x $20; 2x $10's; 1x $5; and 5x $1's. All remaining money and other equipment go to the Bank. \n ");
                        printf("Banker: Select as Banker a player/volunteer who will also make a good Auctioneer. If the Banker plays in the game, he/she must keep his/her personal funds separate from those of the Bank. \n");
                        printf("The Bank: Besides the Bank's money, the Bank holds the Title Deed cards and houses and hotels prior to purchase and use by the players. The Bank pays salaries ($200 for passing “GO”) and bonuses. It sells and auctions properties and hands out their proper Title Deed cards; it sells houses and hotels to the players and lends money when required on mortgages. The Bank collects all taxes, fines, loans and interest, and the price of all properties, which it sells and auctions. The Bank never “goes broke.” If the Bank runs out of money, it may issue as much more as may be needed by merely writing on any ordinary piece of paper. \n");
                        printf("The Play Starting with the Banker, each player in turn throws the dice. The player with the highest total starts the play. He/she places his/her token on the corner marked “GO,” throws the 2 dice and moves his/her token in the direction of the arrow the number of spaces indicated by the dice. After he/she has completed his/her play, the turn to play passes to the left. The tokens remain on the spaces occupied and proceed from that point on the player's next turn. Two or more tokens may rest on the same space at the same time. According to the space, which his/her token reaches, a player may be entitled to buy real estate or other properties - or be obliged to pay rent, pay taxes, draw a Chance or Community Chest card, “Go to Jail,” etc. \n");
                        printf("Doubles If a player throws doubles, he/she moves his/her token as usual, the sum of the two dice, and is subject to any privileges or penalties pertaining to the space on which he/she lands. Retaining the dice, he/she throws again and moves his/her token as before. If a player throws doubles three times in succession, he/she moves his/her token immediately to the space marked “In Jail” (see JAIL). \n");
                        printf("GO Each time a player's token lands on or passes over GO, whether by throw of the dice or by drawing a card, the Banker pays the player a $200 salary. The $200 is paid only once each time around the board. However, if a player passing GO on the throw of a dice lands 2 spaces beyond it on Community Chest, or 7 spaces beyond it on Chance, and draws the “Advance to GO” card, he/she collects $200 for passing GO the first time and another $200 for reaching it the second time by instructions on the card. \n");
                        printf("Buying Property Whenever a player lands on an unowned property, the player may buy that property from the Bank at its printed price. The player receives the Title Deed card showing ownership and places it face up in front of him/her. If he/she does not wish to buy the property, it is immediately sold at auction by the Banker to the highest bidder. The buyer pays to the Bank the amount of the bid in cash and receives the Title Deed card for that property. Any player, including the one who declined the option of buying it at the printed price, may bid. Bidding may start at any price. \n");
                        printf("Paying Rent When a player lands on a property owned by another player, the owner collects rent from the player in accordance with the list printed on the Title Deed card applying to it. If the property is mortgaged, no rent can be collected. When a property is mortgaged, its Title Deed card is placed face down in front of the owner. It is an advantage to hold all the Title Deed cards in a color-group (i.e. Boardwalk and Park Place, or Connecticut, Vermont and Oriental Avenues) because the owner may then charge double rent for unimproved properties in that color-group. This rule applies to unmortgaged properties even if another property in that color-group is mortgaged. It is even more of an advantage to have houses and hotels on properties because rents are much higher than for unimproved properties. The owner may not collect his/her rent if he/she fails to ask for it before the second player following throws the dice. \n");
                        printf("Chance and Community Chest When a player lands on either of these spaces he/she takes the top card from the deck indicated, follows the instruction, and returns the card face down to the bottom of the deck. The “Get Out of Jail Free” card is held until used and then returned to the bottom of the deck. If the player who draws does not wish to use it he/she may sell it, at any time, to another player at a price agreeable to both.  \n");
                        printf("Income Tax When a player lands on “Income Tax” he/she must pay the $200 tax to the Bank. \n");
                        printf("Jail A player lands in jail when...(1) his/her token lands on the space marked “Go to Jail”; (2) he/she draws a card marked “Go to Jail”; (3) he/she throws doubles three times in succession. When a player is sent to Jail he/she cannot collect $200 salary in that move since, regardless of where his/her token is on the board, he/she must move it directly into Jail. A player's turn ends when he/she is sent to Jail. If a player is not “sent to Jail” but in the ordinary course of play lands on that space, he/she is “Just Visiting,” incurs no penalty, and moves ahead in the usual manner on his/her next roll. \n");
                        printf("A player gets out of Jail by (1) throwing doubles on any of his/her next three turns, if he/she succeeds in doing this he/she immediately moves forward the number of spaces shown by his/her doubles throw, even though he/she had thrown doubles, he/she does not take another turn; (2) using the “Get Out of Jail Free” card if he/she has it; (3) purchasing the “Get Out of Jail Free” card from another player and playing it; (4) paying a fine of $50 before he/she rolls the dice on either of his/her next two turns. If the player does not throw doubles by his/her third turn, he/she must pay the $50 fine. He/she then gets out of Jail and immediately moves forward the number of spaces shown by his/her throw. Even though he/she is in Jail, a player may still buy, sell, or mortgage property, buy or sell houses and hotels, make trades, and collect rents. \n");
                        printf("Free Parking A player landing on this space does not receive any money, property or reward of any kind. This is just a “free” resting place. \n");
                        printf("Houses When a player owns all the properties in a color-group, he/she may buy houses from the Bank and erect them on those properties. If he/she buys one house, he/she may put it on any one of those properties. The next house the player buys must be erected on one of the unimproved properties of this or any other complete color-group he/she may own. The price the player must pay the Bank for each house is shown on his/her Title Deed card for the property on which he/she erects the house. The owner can still collect double rent from an opponent who lands on the unimproved properties of his/her color-group. \n");
                        printf("Following the above rules, a player may buy and erect (at any time during his/her turn or in between any turns) as many houses as his/her judgment and financial standing will allow. But the player must build evenly, i.e. he/she cannot erect more than one house on any one property of any color-group until he/she has built one house on every property of that group. He/she may then begin on the second row of houses, and so on, up to a limit of four houses to a property. For example, he/she cannot build three houses on one property if he/she has only one house on another property of that group. As a player builds evenly, he/she must also break down evenly as he/she sells houses back to the Bank (see SELLING PROPERTY).\n");
                        printf("Hotels When a player has four houses on each property of a complete color-group, he/she may buy a hotel from the Bank and erect it on any property of the color-group. He/She returns the four houses from that property to the Bank and pays the price for the hotel as shown on the Title Deed card. Only one hotel may be erected on any one property.\n");
                        printf("Building Shortage When the Bank has no houses to sell, players wishing to build must wait for another player to turn back or sell his/her houses to the Bank before building. If there are a limited number of houses and hotels available, and two or more players wish to buy more than the Bank has, the houses or hotels must be sold one at a time at auction to the highest bidder. Each house/hotel auction begins at the price of the lowest priced house/hotel desired for purchase among the bidding players. \n");
                        printf("Selling/Trading Property Unimproved properties, railroads and utilities (but not buildings) may be sold or traded to any player as a private transaction for any amount that the owner can get. However, no property can be sold to another player if buildings are standing on any properties of that color-group. Any buildings so located must be sold back to the Bank before the owner can sell or trade any property of that color-group. Houses and hotels may be sold back to the Bank at any time for one-half the price paid for them. All houses on one color-group must be sold one by one, evenly, in reverse of the manner in which they were erected. All hotels on one color-group may be sold at once. Or they may be sold one house at a time (one hotel equals five houses), evenly, in reverse of the manner in which they were erected. \n");
                        printf("Mortgages Unimproved properties can be mortgaged through the Bank at any time. Before an improved property can be mortgaged, all the buildings on all the properties of its color-group must be sold back to the Bank at half price. The mortgage value is printed on each Title Deed card. No rent can be collected on mortgaged properties or utilities, but rent may be collected on unmortgaged properties in the same color group. In order to lift the mortgage, the owner must pay the Bank the amount of the mortgage plus 10% interest. When all the properties of a color-group are no longer mortgaged, the owner may begin to buy back houses at full price. The player who mortgages property retains possession of it and no other player may secure it by lifting the mortgage from the Bank. However, the owner may sell or trade this mortgaged property to another player at any agreed price. The new owner may lift the mortgage at once, if he/she wishes, by paying off the mortgage plus 10% interest to the Bank. If he/she does not lift the mortgage at once, he/she must pay the bank 10% interest when he/she buys/receives the mortgaged property, and if he/she lifts the mortgage later he/she must pay the Bank an additional 10% interest as well as the amount of the mortgage. \n");
                        printf("Bankruptcy A player is bankrupt when he/she owes more than he/she can pay either to another player or to the Bank. If his/her debt is to another player, he/she must turn over to that player all that he/she has of value and retire from the game. In making this settlement, if he/she owns houses or hotels, he/she must return these to the Bank in exchange for money to the extent of onehalf the amount paid for them and this cash is given to the creditor. If he/she has mortgaged property, he/she also turns his/her property over to this creditor but the new owner must at once pay the Bank the amount of interest on the loan, which is 10% of the value of the property. After the new owner does this, he/she may, at his/her option, pay the principal or hold the property until some later turn at which time he/she may lift the mortgage. If he/she holds property in this way until a later turn, he/she must pay the interest again when he/she lifts the mortgage. \n");
                        printf("Should a player owe the Bank, instead of another player, more than he/she can pay (because of taxes or penalties) even by selling his/her buildings, mortgaging property, or selling/trading with other players, then he/she must turn over all his/her assets to the Bank. In this case, the Bank immediately sells by auction all property so taken, except buildings. A bankrupt player must immediately retire from the game. The last player left in the game wins. \n");
                        printf("Miscellaneous Money can only be loaned to a player by the Bank and then only by mortgaging property. No player may borrow from or lend money to another player. \n");
        }}
        //copied from http://avcschool.com/wp-content/uploads/2013/02/HDMC-Basic-Rules.pdf
        return;
}


